### ISSUE TITLE
Internet issue

### ISSUE THREAD

**Issue by SirHalo** [RedLime/ModCheck#10]
Sure you've seen the issue, I assume you're repairing your servers or something along those lines.

Error:
java.lang.IllegalAccessException: Couldn't loading url request data! check your internet status
	at com.pistacium.modcheck.util.ModCheckUtils.getUrlRequest(ModCheckUtils.java:43)
	at com.pistacium.modcheck.ModCheck.lambda$main$0(ModCheck.java:51)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by AyuubHassan** [comment]
hmm i have never seen this

**Comment by SrDinoh** [comment]
java.lang.IllegalAccessException: Couldn't loading url request data! check your internet status
	at com.pistacium.modcheck.util.ModCheckUtils.getUrlRequest(ModCheckUtils.java:43)
	at com.pistacium.modcheck.ModCheck.lambda$main$0(ModCheck.java:51)
	at com.pistacium.modcheck.ModCheck$$Lambda$1/1705736037.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by hlswan** [comment]
I am also getting this error:
java.lang.IllegalAccessException: Couldn't loading url request data! check your internet status
	at com.pistacium.modcheck.util.ModCheckUtils.getUrlRequest(ModCheckUtils.java:43)
	at com.pistacium.modcheck.ModCheck.lambda$main$0(ModCheck.java:51)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
