### ISSUE TITLE
Error Exception! when loading the mod list.

### ISSUE THREAD

**Issue by SL0PPYS4L4M1** [RedLime/ModCheck#6]
Getting this error after a couple seconds of waiting for the mod list to load. Says I should check my internet status but there isn't anything wrong with my internet that I have been able to find. Not sure what to do about this.

java.lang.IllegalAccessException: Couldn't loading url request data! check your internet status
	at com.pistacium.modcheck.util.ModCheckUtils.getUrlRequest(ModCheckUtils.java:43)
	at com.pistacium.modcheck.ModCheck.lambda$main$0(ModCheck.java:51)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by RedLime** [comment]
it is fixed rn :) I was maintaining my server
