### ISSUE TITLE
Error exception

### ISSUE THREAD

**Issue by DerekShig** [RedLime/ModCheck#9]
When opening ModCheck v0.5.3, I get an error stating that it could not load url request data.

Logs:

java.lang.IllegalAccessException: Couldn't loading url request data! check your internet status
  at com.pistacium.modcheck.util.ModCheckUtils.getUrlRequest(ModCheckUtils.java:43)
  at com.pistacium.modcheck.ModCheck.lambda$main$0(ModCheck.java:51)
  at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
  at java.base/java.lang.Thread.run(Thread.java:1589)

**Comment by RedLime** [comment]
currently my domain server is dead. please wait until it is back
